<?php
/**
 * Created by PhpStorm.
 * User: hongmj
 * Date: 2018/6/6
 * Time: 22:48
 */
namespace App;
use System\Core\ApplicationBase;

class Application extends ApplicationBase{
    public static function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}